[build]
  command = "npm run build:netlify-lambda apps/api/src"
  functions = "apps/api/functions"
  publish = "apps/api/functions"


[dev]
  command = "npm run start:netlify-lambda apps/api/src"
  port = 3333
  targetPort = 9000
  publish = "apps/api/functions"
  autoLaunch = true
